image: docker:stable
services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

before_script:
  - docker info
  - docker version

.build:
  stage: build
  script:
    -   |
        docker build --pull \
        --build-arg BASE_IMAGE_VERSION=$BASE_IMAGE_VERSION  \
        --build-arg JULIA_MAJOR=$JULIA_MAJOR \
        --build-arg JULIA_VERSION=$JULIA_VERSION \
        --build-arg JULIA_SHA256=$JULIA_SHA256 \
        --build-arg PLJULIA_PACKAGES="CpuId,Primes" \
        --build-arg PLJULIA_REGRESSION=YES \
        -t           pljulia:$CI_BUILD_NAME .
    -  docker images pljulia:$CI_BUILD_NAME
    -  docker images $BASE_IMAGE_VERSION


# -----------------------------------
# --------- Julia 1.7-rc1 ----------
# -----------------------------------

pg14-jl1.7rc1:
  extends: .build
  allow_failure: true
  variables:
    BASE_IMAGE_VERSION: 'postgres:14-bullseye'
    JULIA_MAJOR: '1.7'
    JULIA_VERSION: '1.7.0-rc1'
    JULIA_SHA256: '3c31b79d644eef21811732a1a69bd3d9f23e4b8b19b2856874b02b8fa6a63254'

pg13-jl1.7rc1:
  extends: .build
  allow_failure: true
  variables:
    BASE_IMAGE_VERSION: 'postgres:13-bullseye'
    JULIA_MAJOR: '1.7'
    JULIA_VERSION: '1.7.0-rc1'
    JULIA_SHA256: '3c31b79d644eef21811732a1a69bd3d9f23e4b8b19b2856874b02b8fa6a63254'

# ------------------------------
# --------- Julia 1.6 ----------
# ------------------------------


pg13-jl1.6:
  extends: .build
  allow_failure: false
  variables:
    BASE_IMAGE_VERSION: 'postgres:13-bullseye'
    JULIA_MAJOR: '1.6'
    JULIA_VERSION: '1.6.3'
    JULIA_SHA256: 'c7459c334cd7c3e4a297baf52535937c6bad640e60882f9201a73bab9394314b'

pg12-jl1.6:
  extends: .build
  allow_failure: true
  variables:
    BASE_IMAGE_VERSION: 'postgres:12-bullseye'
    JULIA_MAJOR: '1.6'
    JULIA_VERSION: '1.6.3'
    JULIA_SHA256: 'c7459c334cd7c3e4a297baf52535937c6bad640e60882f9201a73bab9394314b'

pg11-jl1.6:
  extends: .build
  allow_failure: true
  variables:
    BASE_IMAGE_VERSION: 'postgres:11-bullseye'
    JULIA_MAJOR: '1.6'
    JULIA_VERSION: '1.6.3'
    JULIA_SHA256: 'c7459c334cd7c3e4a297baf52535937c6bad640e60882f9201a73bab9394314b'

# ----
# pg10-jl1.6:
#   extends: .build
#   allow_failure: true
#   variables:
#     BASE_IMAGE_VERSION: 'postgres:10-bullseye'
#     JULIA_MAJOR: '1.6'
#    JULIA_VERSION: '1.6.3'
#    JULIA_SHA256: 'c7459c334cd7c3e4a297baf52535937c6bad640e60882f9201a73bab9394314b'
#
# pg9.6-jl1.6:
#   extends: .build
#   allow_failure: true
#   variables:
#     BASE_IMAGE_VERSION: 'postgres:9.6-bullseye'
#     JULIA_MAJOR: '1.6'
#    JULIA_VERSION: '1.6.3'
#    JULIA_SHA256: 'c7459c334cd7c3e4a297baf52535937c6bad640e60882f9201a73bab9394314b'
#

# ------------------------------
# --------- Julia 1.0 ----------
# ------------------------------

# pg9.6-jl1.0:
#   extends: .build
#   allow_failure: true
#   variables:
#     BASE_IMAGE_VERSION: 'postgres:9.6-bullseye'
#     JULIA_MAJOR: '1.0'
#     JULIA_VERSION: '1.0.5'
#     JULIA_SHA256: '9dedd613777ba6ebd8aee5796915ff50aa6188ea03ed143cb687fc2aefd76b03'

pg13-jl1.0:
  extends: .build
  allow_failure: true
  variables:
    BASE_IMAGE_VERSION: 'postgres:13-bullseye'
    JULIA_MAJOR: '1.0'
    JULIA_VERSION: '1.0.5'
    JULIA_SHA256: '9dedd613777ba6ebd8aee5796915ff50aa6188ea03ed143cb687fc2aefd76b03'
